version: '3.7'
services:
  spark-master:
    image: karmaterminal/spark-master:${SPARK_VERSION}
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
      - "6066:6066"
      - "4040:4040"
    environment:
      - INIT_DAEMON_STEP=setup_spark
    volumes:
      - /data/spark/task_usage/:/task_usage
      - /data/spark/machine_events:/machine_events
      - /data:/data
    networks:
      - spark-network
  spark-worker:
    image: karmaterminal/spark-worker:${SPARK_VERSION}
    depends_on:
      - spark-master
    ports:
      - "8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "SPARK_WORKER_CORES=32"
      - "SPARK_WORKER_MEMORY=128g"
      - "SPARK_EXECUTOR_MEMORY=32g"
      - "SPARK_EXECUTOR_CORES=8"
      - "SPARK_DRIVER_MEMORY=32g"
    volumes:
      - /data/spark/task_usage/:/task_usage
      - /data/spark/machine_events:/machine_events
      - /data:/data
    networks:
      - spark-network
  zeppelin:
    image: karmaterminal/zeppelin:latest
    container_name: zeppelin
    environment:
      JAVA_INTP_OPTS: "-Xmx128g"
      SPARK_SUBMIT_OPTIONS: "--driver-memory 32g --executor-memory 32g"
      ZEPPELIN_PORT: 8090
      ZEPPELIN_JAVA_OPTS: >-
        -Dspark.executor.memory=32g
        -Dspark.driver.memory=32g
        -Dspark.executor.cores=8
        -Dspark.dynamicAllocation.enabled=true
        -Dspark.shuffle.service.enabled=true
        -Dspark.driver.maxResultSize=128g
       
      MASTER: "spark://spark-master:7077"
    ports:
      - 8090:8090
    networks:
      - spark-network
    volumes:
      - /data:/data
      - /data/zeppelin/notebook:/zeppelin/notebook
      - /data/zeppelin/logs:/zeppelin/logs
networks:
  spark-network:
    driver: bridge
    ipam:
      driver: default
